import { useState, useEffect, useCallback } from 'react';
import { Plus, Megaphone, Pencil, Trash2, X, ExternalLink, Film, Image as ImageIcon, ChevronRight, Layers } from 'lucide-react';
import { api } from '../../api.js';
import { C, FONT, MONO } from '../../constants.js';
import { showError, showSuccess } from '../../lib/feedback.js';
import { useConfirm } from '../../components/ConfirmDialog.jsx';
import SearchableSelect from '../../components/SearchableSelect.jsx';
import { useFunnelConfig } from '../../hooks/useFunnelConfig.js';
import { PageShell, Button, Table, Td, Badge, EmptyState, Modal, Field, inputStyle, fmtINR, fmtDate } from '../academy/shared.jsx';
import { Card, BarChart, Shimmer } from '../../components/charts.jsx';

const STATUS_META = { active: { c: 'var(--c-successText, #0F6E56)', b: 'var(--c-successBg, #E1F5EE)' }, paused: { c: 'var(--c-warnText, #854F0B)', b: 'var(--c-warnBg, #FAEEDA)' }, ended: { c: 'var(--c-textSecondary, #6B7280)', b: 'var(--c-surfaceMuted, #F1F1EE)' } };

export default function CampaignsPage({ user }) {
  const isAdmin = user?.role === 'admin';
  const [rows, setRows] = useState(null);
  const [edit, setEdit] = useState(null);
  const [popup, setPopup] = useState(null);
  const [confirmEl, confirm] = useConfirm();

  const load = useCallback(async () => {
    try { const d = await api.campaigns.list(); setRows(d.campaigns); }
    catch (e) { showError(e.message); }
  }, []);
  useEffect(() => { load(); }, [load]);

  async function del(c) {
    if (!(await confirm({ title: 'Delete campaign?', body: `“${c.name}” will be removed.`, confirmLabel: 'Delete', danger: true }))) return;
    try { await api.campaigns.delete(c.id); showSuccess('Campaign deleted.'); load(); }
    catch (e) { showError(e.message); }
  }

  const chartData = (rows || []).slice(0, 8).map(c => ({ label: c.name.split(' ')[0], value: c.leadsGenerated }));

  return (
    <PageShell
      title="Campaigns"
      subtitle="Ad spend & ROI. Meta-synced campaigns come from Meta Ads Manager (connect it in Admin Settings → Integrations); add manual campaigns for other channels."
      actions={<Button variant="primary" icon={Plus} onClick={() => setEdit({})}>New Campaign</Button>}
    >

      {rows && rows.length > 0 && (
        <Card title="Leads generated by campaign" style={{ marginBottom: 16 }}>
          <BarChart data={chartData} />
        </Card>
      )}

      {!rows ? <Shimmer height={260} radius={12} /> : (
        <Table
          columns={[{ label: 'Campaign' }, { label: 'Platform' }, { label: 'Status' }, { label: 'Spend', align: 'right' },
            { label: 'Leads', align: 'right' }, { label: 'Cost/Lead', align: 'right' }, { label: 'Cost/Enroll', align: 'right' }, { label: 'Dates' }, { label: '', align: 'right' }]}
          rows={rows} keyOf={c => c.id}
          empty={<EmptyState Icon={Megaphone} title="No campaigns yet" hint="Connect Meta Ads or add a campaign to track spend and ROI." />}
          onRowClick={(c) => c.source === 'meta' && setPopup(c)}
          renderRow={(c) => {
            const sm = STATUS_META[c.status] || STATUS_META.active;
            const isMeta = c.source === 'meta';
            return (
              <>
                <Td bold>
                  <span style={{ display: 'inline-flex', alignItems: 'center', gap: 7 }}>
                    {c.name}
                    {isMeta && <span title={`Synced from Meta Ads${c.accountName ? ` · ${c.accountName}` : ''}`}
                      style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.04em', color: '#1877F2', background: 'var(--c-infoBg, #E7F0FE)', padding: '2px 6px', borderRadius: 5, fontFamily: MONO }}>META</span>}
                  </span>
                </Td>
                <Td color={C.textSecondary}>{c.platform || '—'}</Td>
                <Td><Badge label={c.status} color={sm.c} bg={sm.b} style={{ textTransform: 'capitalize' }} /></Td>
                <Td align="right" mono>{fmtINR(c.spend)}</Td>
                <Td align="right" mono>{c.leadsGenerated}</Td>
                <Td align="right" mono>{c.costPerLead != null ? fmtINR(c.costPerLead) : '—'}</Td>
                <Td align="right" mono>{c.costPerEnrollment != null ? fmtINR(c.costPerEnrollment) : '—'}</Td>
                <Td color={C.textMuted} style={{ fontSize: 13 }}>{fmtDate(c.startDate)} – {fmtDate(c.endDate)}</Td>
                <Td align="right">
                  {isMeta ? (
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 13, color: C.primary, fontFamily: FONT, fontWeight: 600 }} title="Break this campaign down into its ad sets and ads">
                      Ad sets &amp; ads <ChevronRight size={14} />
                    </span>
                  ) : (
                    <span style={{ display: 'inline-flex', gap: 4 }}>
                      <button onClick={(e) => { e.stopPropagation(); setEdit(c); }} style={iconBtn}><Pencil size={14} /></button>
                      {isAdmin && <button onClick={(e) => { e.stopPropagation(); del(c); }} style={iconBtn}><Trash2 size={14} /></button>}
                    </span>
                  )}
                </Td>
              </>
            );
          }}
        />
      )}

      {edit && <CampaignModal campaign={edit} onClose={() => setEdit(null)} onSaved={() => { setEdit(null); load(); }} />}
      {popup && <CampaignAdsPopup campaign={popup} onClose={() => setPopup(null)} />}
      {confirmEl}
    </PageShell>
  );
}

const iconBtn = { background: 'none', border: 'none', cursor: 'pointer', color: C.textMuted, padding: 5, borderRadius: 6 };

// ── Campaign → Ad Set → Ad drill-in ──────────────────────────────────────────
//
// Meta's own hierarchy is Campaign → Ad Set → Ad, and the ad set is where the
// decisions live (audience, placement, optimisation goal, budget). A flat list
// of ads hid that entirely, so a weak ad and a weak ad set looked identical.
// Each ad set is a collapsible group carrying its own metrics; ads nest inside.
function CampaignAdsPopup({ campaign, onClose }) {
  const [data, setData] = useState(null);
  const [open, setOpen] = useState({});

  useEffect(() => {
    api.campaigns.ads(campaign.id)
      .then(d => {
        // During a deploy the new bundle can briefly hit the old API, which
        // returns ads with no adsets key. Fall back to one Ungrouped bucket so
        // the drill-in shows the ads instead of a misleading "No ads found".
        const adsets = d.adsets || (d.ads?.length
          ? [{ adsetExternalId: null, name: 'Ungrouped', synced: false, spend: null, leads: null, ads: d.ads }]
          : []);
        setData({ ...d, adsets });
        // Expand the biggest spender by default — the one you came to look at.
        const first = adsets[0];
        if (first) setOpen({ [first.adsetExternalId || '__ungrouped__']: true });
      })
      .catch(e => { showError(e.message); setData({ ads: [], adsets: [] }); });
  }, [campaign.id]);

  useEffect(() => {
    const onKey = (e) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [onClose]);

  const adsets = data?.adsets || [];
  const adCount = (data?.ads || []).length;
  const allOpen = adsets.length > 0 && adsets.every(s => open[s.adsetExternalId || '__ungrouped__']);

  return (
    <div onClick={onClose}
      style={{ position: 'fixed', inset: 0, zIndex: 300, background: 'rgba(0,0,0,.45)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '24px 16px' }}>
      <style>{`
        @keyframes campPopIn { from { opacity: 0; transform: translateY(28px); } to { opacity: 1; transform: translateY(0); } }
      `}</style>
      <div onClick={e => e.stopPropagation()}
        style={{ position: 'relative', width: 'min(940px, 100%)', maxHeight: '88vh', overflowY: 'auto',
          background: C.pageBg, borderRadius: 16, boxShadow: C.shadowLg, fontFamily: FONT,
          animation: 'campPopIn .22s ease-out' }}>
        <div style={{ position: 'sticky', top: 0, background: C.headerBg, color: C.headerText,
          padding: '15px 20px', display: 'flex', alignItems: 'center', gap: 12, zIndex: 2, borderRadius: '16px 16px 0 0' }}>
          <div style={{ minWidth: 0, flex: 1 }}>
            <div style={{ fontSize: 16, fontWeight: 700 }}>{campaign.name}</div>
            <div style={{ fontSize: 13, color: C.headerMuted, fontFamily: MONO, marginTop: 2 }}>
              {campaign.accountName || 'Meta Ads'} · {fmtINR(campaign.spend)} spend · {campaign.leadsGenerated} leads
              {campaign.objective ? ` · ${campaign.objective.replace(/^OUTCOME_/, '')}` : ''}
            </div>
          </div>
          <button onClick={onClose} title="Close"
            style={{ background: 'none', border: 'none', color: C.headerText, cursor: 'pointer', padding: 4 }}>
            <X size={20} />
          </button>
        </div>

        <div style={{ padding: '18px 20px 26px' }}>
          {data == null ? <Shimmer height={160} radius={12} /> : adsets.length === 0 ? (
            <EmptyState Icon={Megaphone} title="No ads found" hint="This campaign has no synced ads yet." />
          ) : (
            <>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14, flexWrap: 'wrap',
                fontSize: 14, color: C.textSecondary, fontFamily: MONO }}>
                <Layers size={14} color={C.textMuted} />
                {adsets.length} ad set{adsets.length !== 1 ? 's' : ''} · {adCount} ad{adCount !== 1 ? 's' : ''}
                <button onClick={() => {
                  const next = {};
                  adsets.forEach(s => { next[s.adsetExternalId || '__ungrouped__'] = !allOpen; });
                  setOpen(next);
                }}
                  style={{ marginLeft: 'auto', background: 'none', border: 'none', cursor: 'pointer',
                    color: C.primary, fontFamily: FONT, fontSize: 14, fontWeight: 600 }}>
                  {allOpen ? 'Collapse all' : 'Expand all'}
                </button>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {adsets.map(s => {
                  const key = s.adsetExternalId || '__ungrouped__';
                  return (
                    <AdSetGroup key={key} adset={s} expanded={!!open[key]}
                      onToggle={() => setOpen(o => ({ ...o, [key]: !o[key] }))} />
                  );
                })}
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// One ad set: its own header metrics, with its ads nested underneath.
function AdSetGroup({ adset: s, expanded, onToggle }) {
  const sm = STATUS_META[s.status] || null;
  // An unsynced stub has no Meta metrics of its own — total its ads instead and
  // label the column, rather than showing a confident ₹0.
  const derived = !s.synced;
  const spend = derived ? s.ads.reduce((n, a) => n + (a.spend || 0), 0) : s.spend;
  const leads = derived ? s.ads.reduce((n, a) => n + (a.leads || 0), 0) : s.leads;
  const cpl = leads ? spend / leads : null;

  return (
    <div style={{ background: C.cardBg, border: `1px solid ${C.border}`, borderRadius: 12, overflow: 'hidden' }}>
      <div onClick={onToggle}
        style={{ display: 'flex', alignItems: 'center', gap: 11, padding: '13px 15px', cursor: 'pointer',
          background: expanded ? C.surfaceAlt : C.cardBg, borderBottom: expanded ? `1px solid ${C.border}` : 'none' }}
        onMouseEnter={e => { if (!expanded) e.currentTarget.style.background = C.hover; }}
        onMouseLeave={e => { if (!expanded) e.currentTarget.style.background = C.cardBg; }}>
        <ChevronRight size={16} color={C.textMuted}
          style={{ flexShrink: 0, transform: expanded ? 'rotate(90deg)' : 'none', transition: 'transform .15s' }} />
        <Layers size={15} color={C.textSecondary} style={{ flexShrink: 0 }} />
        <div style={{ minWidth: 0, flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 7, flexWrap: 'wrap' }}>
            <span style={{ fontSize: 15, fontWeight: 600, color: C.text }}>{s.name}</span>
            {sm && <Badge label={s.status} color={sm.c} bg={sm.b} style={{ textTransform: 'capitalize' }} />}
            <span style={{ fontSize: 13, color: C.textMuted, fontFamily: MONO }}>
              {s.ads.length} ad{s.ads.length !== 1 ? 's' : ''}
            </span>
          </div>
          <div style={{ fontSize: 13, color: C.textMuted, fontFamily: MONO, marginTop: 2 }}>
            {s.optimizationGoal ? `Optimising for ${prettyGoal(s.optimizationGoal)}` : 'Optimisation goal not synced'}
            {s.dailyBudget != null && ` · ${fmtINR(s.dailyBudget)}/day`}
            {s.dailyBudget == null && s.lifetimeBudget != null && ` · ${fmtINR(s.lifetimeBudget)} lifetime`}
            {s.synced && s.dailyBudget == null && s.lifetimeBudget == null && ' · budget set at campaign level'}
          </div>
        </div>
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
          <Metric label={derived ? 'Spend (ads)' : 'Spend'} value={fmtINR(spend)} />
          <Metric label="Leads" value={leads} />
          <Metric label="Cost/Lead" value={cpl != null ? fmtINR(cpl) : '—'} />
          {!derived && <Metric label="Reach" value={s.reach ? s.reach.toLocaleString('en-IN') : '—'} />}
        </div>
      </div>

      {expanded && (
        <div style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 12, background: C.pageBg }}>
          {s.ads.length === 0
            ? <div style={{ fontSize: 14, color: C.textMuted }}>No ads in this ad set.</div>
            : s.ads.map(a => <AdCard key={a.id} ad={a} />)}
        </div>
      )}
    </div>
  );
}

// OUTCOME_LEADS / LINK_CLICKS / CONVERSATIONS → readable words.
function prettyGoal(goal) {
  return String(goal).toLowerCase().replace(/_/g, ' ');
}

const OBJ_ICON = { VIDEO: Film, SHARE: ImageIcon, PHOTO: ImageIcon };

function AdCard({ ad }) {
  const ObjIcon = OBJ_ICON[ad.objectType] || ImageIcon;
  const sm = STATUS_META[ad.status] || null;
  return (
    <div style={{ background: C.cardBg, border: `1px solid ${C.border}`, borderRadius: 11, overflow: 'hidden' }}>
      <div style={{ display: 'flex', gap: 12, padding: 13 }}>
        <div style={{ width: 78, height: 78, borderRadius: 8, background: C.hover, flexShrink: 0, overflow: 'hidden', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          {ad.thumbnailUrl
            ? <img src={ad.thumbnailUrl} alt="" referrerPolicy="no-referrer" style={{ width: '100%', height: '100%', objectFit: 'cover' }} onError={e => { e.currentTarget.style.display = 'none'; }} />
            : <ObjIcon size={24} color={C.textMuted} />}
        </div>
        <div style={{ minWidth: 0, flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 3, flexWrap: 'wrap' }}>
            <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.04em', color: C.textSecondary, background: C.hover, padding: '2px 6px', borderRadius: 4, fontFamily: MONO }}>{ad.objectType || 'AD'}</span>
            <span style={{ fontSize: 15, fontWeight: 600, color: C.text, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{ad.name}</span>
            {sm && <Badge label={ad.status} color={sm.c} bg={sm.b} style={{ textTransform: 'capitalize' }} />}
          </div>
          {(ad.title || ad.body) && (
            <div style={{ fontSize: 14, color: C.textSecondary, lineHeight: 1.45, maxHeight: 52, overflow: 'hidden' }}>{ad.title || ad.body}</div>
          )}
          <div style={{ display: 'flex', gap: 14, marginTop: 8, flexWrap: 'wrap' }}>
            <Metric label="Spend" value={fmtINR(ad.spend)} />
            <Metric label="Leads" value={ad.leads} />
            <Metric label="Cost/Lead" value={ad.costPerLead != null ? fmtINR(ad.costPerLead) : '—'} />
            <Metric label="Clicks" value={ad.clicks?.toLocaleString('en-IN')} />
            <Metric label="Impressions" value={ad.impressions?.toLocaleString('en-IN')} />
          </div>
        </div>
      </div>
      {ad.igPermalink && (
        <div style={{ borderTop: `1px solid ${C.border}`, padding: '8px 13px' }}>
          <a href={ad.igPermalink} target="_blank" rel="noreferrer"
            style={{ color: C.primary, display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 13, fontWeight: 600, textDecoration: 'none' }}>
            View this ad on Instagram <ExternalLink size={11} />
          </a>
        </div>
      )}
    </div>
  );
}

function Metric({ label, value }) {
  return (
    <div>
      <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.06em', color: C.textMuted, textTransform: 'uppercase' }}>{label}</div>
      <div style={{ fontSize: 15, fontWeight: 700, fontFamily: MONO, color: C.text, marginTop: 1 }}>{value ?? '—'}</div>
    </div>
  );
}

function CampaignModal({ campaign, onClose, onSaved }) {
  const { sources } = useFunnelConfig();
  const isNew = !campaign.id;
  const [f, setF] = useState({
    name: campaign.name || '', platform: campaign.platform || '', status: campaign.status || 'active',
    spend: campaign.spend || 0, leadsGenerated: campaign.leadsGenerated || 0, enrollments: campaign.enrollments || 0,
    startDate: campaign.startDate?.slice(0, 10) || '', endDate: campaign.endDate?.slice(0, 10) || '',
  });
  const [saving, setSaving] = useState(false);
  const set = (k) => (e) => setF(s => ({ ...s, [k]: e.target?.value ?? e }));
  async function save() {
    if (!f.name.trim()) return showError('Campaign name is required');
    setSaving(true);
    try {
      if (isNew) await api.campaigns.create(f); else await api.campaigns.update(campaign.id, f);
      showSuccess(isNew ? 'Campaign created.' : 'Campaign updated.'); onSaved();
    } catch (e) { showError(e.message); setSaving(false); }
  }
  return (
    <Modal title={isNew ? 'New Campaign' : 'Edit Campaign'} onClose={onClose}
      footer={<><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="primary" onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save'}</Button></>}>
      <Field label="Name *"><input style={inputStyle} value={f.name} onChange={set('name')} autoFocus /></Field>
      <div style={{ display: 'flex', gap: 10 }}>
        <div style={{ flex: 1 }}><Field label="Platform">
          <SearchableSelect value={f.platform} onChange={v => setF(s => ({ ...s, platform: v }))} options={sources.map(x => ({ value: x, label: x }))} placeholder="Platform" createLabel="Use custom" onCreate={() => setF(s => ({ ...s, platform: '' }))} />
        </Field></div>
        <div style={{ flex: 1 }}><Field label="Status">
          <SearchableSelect value={f.status} onChange={v => setF(s => ({ ...s, status: v }))} options={['active', 'paused', 'ended'].map(x => ({ value: x, label: x }))} />
        </Field></div>
      </div>
      <div style={{ display: 'flex', gap: 10 }}>
        <div style={{ flex: 1 }}><Field label="Spend (₹)"><input type="number" style={inputStyle} value={f.spend} onChange={set('spend')} /></Field></div>
        <div style={{ flex: 1 }}><Field label="Leads"><input type="number" style={inputStyle} value={f.leadsGenerated} onChange={set('leadsGenerated')} /></Field></div>
        <div style={{ flex: 1 }}><Field label="Enrollments"><input type="number" style={inputStyle} value={f.enrollments} onChange={set('enrollments')} /></Field></div>
      </div>
      <div style={{ display: 'flex', gap: 10 }}>
        <div style={{ flex: 1 }}><Field label="Start date"><input type="date" style={inputStyle} value={f.startDate} onChange={set('startDate')} /></Field></div>
        <div style={{ flex: 1 }}><Field label="End date"><input type="date" style={inputStyle} value={f.endDate} onChange={set('endDate')} /></Field></div>
      </div>
    </Modal>
  );
}
